spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/db/sbb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create # DB 테이블 자동생성(엔티티 클래스만 만들면 됨)
    properties:
      hibernate:
        show_sql: true
        format_sql: true